### ISSUE TITLE
Wrong error message in `deprecate_soft()`

### ISSUE THREAD

**Issue by olivroy** [r-lib/lifecycle#168] opened 2023-07-13 19:26 UTC
Hi,

I made a mistake when using `lifecycle::deprecate_sof()`

``` r
lifecycle::deprecate_soft(
  when = "0.4",
  what = "fn()",
  with = "fn"
)
Error in `lifecycle_message()`:
! `what` must have function call syntax.

  # Good:
  deprecate_soft("fn()")

  # Bad:
  deprecate_soft("fn")
```

<sup>Created on 2023-07-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I believe it should point me to `with` instead of `what`.

# expected error message

```r
Error in `lifecycle_message()`:
! `with` must have function call syntax.
```

**Comment by hadley** [comment] 2023-11-02 15:23
Duplicate of #152

**Closed by hadley** 2023-11-02 15:23 UTC
Labels: feature
