### ISSUE TITLE
Allow `deprecate_*(with = )` to be an expression

### ISSUE THREAD

**Issue by t-kalinowski** [r-lib/lifecycle#118] opened 2022-01-14 16:14 UTC
This is what I'm trying to do in {tfprobability}:
``` R
 lifecycle::deprecate_warn("0.15", "tfb_affine_scalar()", "tfb_shift(shift)(tfb_scale(scale))")
```
I get error:
```
Error: Internal error in lifecycle: `what` must be a function or method call.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by lionel-** [comment] 2022-03-02 13:28
I think we'll allow passing `with = I("string")`, in which case the string is taken as is. So you'd have to supply:

```r
with = I("Please use `tbl_shift(shift)(tfb_scale(scale))` instead.
```

**Comment by hadley** [comment] 2022-08-13 19:15
Duplicate of #120

**Closed by hadley** 2022-08-13 19:15 UTC
