### ISSUE TITLE
rlang: `sexp_address()` has been renamed to `obj_address()`

### ISSUE THREAD

**Issue by hsbadr** [r-lib/lifecycle#112] opened 2021-04-19 12:40 UTC
https://github.com/r-lib/rlang/commit/33f12f3b97af38a9b26ef76e46228b58ff15ebb4 renamed `sexp_address()` to `obj_address()`, which is now exported. So, replace `sexp_address` by the exported `rlang::obj_address` here.

https://github.com/r-lib/lifecycle/blob/19781f7d003383f2c6a155b1a8fd725557eb8103/R/lifecycle-package.R#L14-L15

**Comment by lionel-** [comment] 2021-04-19 13:27
Can you try again, this should be fixed by https://github.com/r-lib/rlang/commit/0731e27944c875ce02c3a9c79040ebc2fccba80d.

**Comment by hsbadr** [comment] 2021-04-19 13:50
> Can you try again, this should be fixed by [r-lib/rlang@0731e27](https://github.com/r-lib/rlang/commit/0731e27944c875ce02c3a9c79040ebc2fccba80d).

No, it doesn't (I left a comment on https://github.com/r-lib/rlang/commit/33f12f3b97af38a9b26ef76e46228b58ff15ebb4). I think that the following line expects `rlang::sexp_address`, which doesn't exist anymore. Couldn't you just replace `sexp_address` here with `rlang::obj_address`? You already import `rlang` and it seems that the line is a hack:
https://github.com/r-lib/lifecycle/blob/19781f7d003383f2c6a155b1a8fd725557eb8103/R/lifecycle-package.R#L14-L15

**Comment by hsbadr** [comment] 2021-04-19 14:15
Or, maybe, export `sexp_address` from `rlang` as an alias of `obj_address`.

**Comment by lionel-** [comment] 2021-04-19 14:47
> Or, maybe, export sexp_address from rlang as an alias of obj_address.

`sexp_address()` has never been exported in a CRAN version of rlang.

> I think that the following line expects rlang::sexp_address, which doesn't exist anymore

It should exist again following the update in https://github.com/r-lib/rlang/commit/0731e27944c875ce02c3a9c79040ebc2fccba80d.

**Comment by hsbadr** [comment] 2021-04-19 15:08
> It should exist again following the update in [r-lib/rlang@0731e27](https://github.com/r-lib/rlang/commit/0731e27944c875ce02c3a9c79040ebc2fccba80d).

Can you test the following:
```r
remotes::install_github("r-lib/rlang", force = TRUE)
remotes::install_github("rstudio/rmarkdown", force = TRUE)
```

After the rename and without exporting `sexp_address`, this fails with:
```r
** byte-compile and prepare package for lazy loading
Error: object ‘sexp_address’ is not exported by 'namespace:rlang'
Execution halted
ERROR: lazy loading failed for package ‘rmarkdown’
```

This happens with many packages, not only `rmarkdown`. It works fine with https://github.com/r-lib/rlang/pull/1167.

**Comment by hsbadr** [comment] 2021-04-19 15:12
@lionel- Ok. This works fine on R-release but fails on R-devel.

**Comment by lionel-** [comment] 2021-04-19 15:52
I can't reproduce on either release and devel R. Is this from a CI or are you testing locally?

**Comment by hadley** [comment] 2021-04-19 16:09
Once rlang is released we should use the exported `obj_address()`

**Comment by hsbadr** [comment] 2021-04-19 16:12
> Once rlang is released we should use the exported `obj_address()`

@hadley Sounds great. Thanks!

> I can't reproduce on either release and devel R. Is this from a CI or are you testing locally?

@lionel- I'm testing locally on the latest R-devel.

```r
> reprex::reprex(remotes::install_github("rstudio/rmarkdown", force = TRUE))
ℹ Rendering reprex...
Error: object ‘sexp_address’ is not exported by 'namespace:rlang'
```
```r
> traceback()
11: stop(sprintf(ngettext(length(miss), "object %s is not exported by 'namespace:%s'",
        "objects %s are not exported by 'namespace:%s'"), paste(sQuote(miss),
        collapse = ", "), getNamespaceName(expenv)), call. = FALSE,
        domain = NA)
10: importIntoEnv(impenv, impnames, ns, impvars)
9: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,
       .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
8: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
7: asNamespace(ns)
6: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,
       .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
5: loadNamespace(x) at reprex_render.R#251
4: reprex_document_options(input) at reprex_render.R#75
3: reprex_render_impl(r_file, new_session = new_session, html_preview = html_preview) at reprex_impl.R#92
2: reprex_impl(x_expr = substitute(x), input = input, wd = wd, venue = venue,
       render = render, new_session = TRUE, advertise = advertise,
       session_info = session_info, style = style, html_preview = html_preview,
       comment = comment, tidyverse_quiet = tidyverse_quiet, std_out_err = std_out_err,
       outfile = outfile) at reprex.R#272
1: reprex::reprex(remotes::install_github("rstudio/rmarkdown", force = TRUE))
```
```r
> sessionInfo()
R Under development (unstable) (2021-04-19 r80187)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS/LAPACK: /opt/intel/oneapi/mkl/2021.2.0/lib/intel64/libmkl_intel_lp64.so.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  utils     datasets  grDevices methods   base

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13      knitr_1.32.3         magrittr_2.0.1.9000
 [4] rlang_0.4.10.9000    fastmap_1.1.0        fansi_0.4.2
 [7] styler_1.4.1.9000    highr_0.9            tools_4.1.0
[10] xfun_0.22.2          utf8_1.2.1           cli_2.4.0.9000
[13] withr_2.4.2          ellipsis_0.3.1.9000  digest_0.6.27.1
[16] tibble_3.1.1.9000    lifecycle_1.0.0.9000 crayon_1.4.1.9000
[19] purrr_0.3.4.9000     vctrs_0.3.7.9000     fs_1.5.0
[22] ps_1.6.0.9000        glue_1.4.2           evaluate_0.14.1
[25] reprex_2.0.0.9000    compiler_4.1.0       pillar_1.6.0.9001
[28] backports_1.2.1      pkgconfig_2.0.3
```

**Comment by lionel-** [comment] 2021-04-19 17:08
The error message mentions a missing exported function but no package ever imported this function. In particular, the lifecycle line you mentioned in your first message, which uses `env_get()`, should produce a missing binding error rather than a non-exported function error, so it doesn't look like it is the culprit. Are you sure lifecycle is involved?

To me this points out to a local rlang installation issue. I would try to remove completely rlang and install it again.

**Comment by hsbadr** [comment] 2021-04-19 17:26
> The error message mentions a missing exported function but no package ever imported this function. In particular, the lifecycle line you mentioned in your first message, which uses `env_get()`, should produce a missing binding error rather than a non-exported function error, so it doesn't look like it is the culprit. Are you sure lifecycle is involved?

The traceback belongs to `rlang` not `lifecycle`. I've merged https://github.com/r-lib/rlang/pull/1167 into my local fork.

> To me this points out to a local rlang installation issue. I would try to remove completely rlang and install it again.

I did remove `rlang` and reinstalled it. I get the same error unless `sexp_address` is exported. It could be a combination of other installed packages that imports `sexp_address` from `rlang`. I'll let you know if/when it's fixed.

In the meanwhile, feel free to close this issue of leave it open until you replace `sexp_address` by `rlang::obj_address` here.

**Comment by hsbadr** [comment] 2021-04-19 17:32
Also, installing `rlang` at any revision, before https://github.com/r-lib/rlang/commit/33f12f3b97af38a9b26ef76e46228b58ff15ebb4, fixes the problem for me:
```r
remotes::install_github("r-lib/rlang@c3ccf3927deb76253a674aa8ddc55b7918479848", force = TRUE)
```

**Comment by hsbadr** [comment] 2021-04-19 17:39
> Can you load rlang at all?

Yes. I can load both `rlang` and `lifcycle`. I think that https://github.com/r-lib/rlang/commit/0731e27944c875ce02c3a9c79040ebc2fccba80d fixes it for `lifecycle` but there's other bug somewhere else because `object ‘sexp_address’ is not exported by 'namespace:rlang'`, specifically with lazy loading of some packages.

**Comment by hsbadr** [comment] 2021-04-19 17:43
@lionel- You might want to check reverse dependencies after https://github.com/r-lib/rlang/commit/33f12f3b97af38a9b26ef76e46228b58ff15ebb4.

**Comment by lionel-** [comment] 2021-04-19 17:48
@hsbadr We systematically check reverse dependencies before release.

Regardless, this function has only ever been exported in the _dev_ version of rlang. It is not possible for a released package to depend on it. I'm not aware of any dev version of a package that imports this function. The renaming should be safe, correct, and backward-compatible. I still think there is an installation issue on your end. It is very strange though.

**Comment by hsbadr** [comment] 2021-04-19 17:51
I see. It could be an issue in my R environment. It's weird that it's fixed when I revert the renaming commit or export `sexp_address`. I'll keep you updated if I find the culprit.

**Comment by lionel-** [comment] 2021-04-21 11:15
@hsbadr Maybe you have the development version of htmltools installed?

https://github.com/r-lib/rlang/pull/1171#issuecomment-823926640

**Comment by hsbadr** [comment] 2021-04-21 11:20
> Maybe you have the development version of htmltools installed?

Yes. I haven't installed the packages from GitHub yet. I'll let you if `htmltools` brings the issue.

**Closed** 2022-08-15 13:05 UTC
